apiVersion : apps/v1
kind: Deployment
metadata:
  name: "kuberdockerimage-2c1d"
spec:
  replicas: 2
  selector:
    matchLabels:
      app: "kuberdockerimage-2c1d"
  template:
    metadata:
      labels:
        app: "kuberdockerimage-2c1d"
    spec:
      containers:
        - name: "kuberdockerimage-2c1d"
          image: "demoregistery1.azurecr.io/kuberdockerimage"
          ports:
          - containerPort: 8080