on: [push]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    
    - uses: azure/docker-login@v1
      with:
        login-server: demoregistery1.azurecr.io
        username: ${{ secrets.acr_demoregistery1_username }}
        password: ${{ secrets.acr_demoregistery1_password }}
    
    - name: Build and push image to ACR
      id: build-image
      run: |
        docker build "$GITHUB_WORKSPACE/SpringAplication-master" -f  "SpringAplication-master/Dockerfile" -t demoregistery1.azurecr.io/kuberdockerimage:${{ github.sha }} --label dockerfile-path=SpringAplication-master/Dockerfile
        docker push demoregistery1.azurecr.io/kuberdockerimage:${{ github.sha }}
    
    - uses: azure/k8s-set-context@v1
      with:
         kubeconfig: ${{ secrets.aks_kuberdockerimage_kubeConfig }}
      id: login
    
    - name: Create namespace
      run: |
        namespacePresent=`kubectl get namespace | grep kuberdockerimagea3ab | wc -l`
        if [ $namespacePresent -eq 0 ]
        then
            echo `kubectl create namespace kuberdockerimagea3ab`
        fi

    - uses: azure/k8s-create-secret@v1
      with:
        namespace: kuberdockerimagea3ab
        container-registry-url: demoregistery1.azurecr.io
        container-registry-username: ${{ secrets.acr_demoregistery1_username }}
        container-registry-password: ${{ secrets.acr_demoregistery1_password }}
        secret-name: kuberdockeridockerauth
       
    - uses: azure/k8s-deploy@v1.2
      with:
        namespace: kuberdockerimagea3ab
        manifests: |
          manifests/deployment.yml
          manifests/service.yml
        images: |
          demoregistery1.azurecr.io/kuberdockerimage:${{ github.sha }}
        imagepullsecrets: |
          kuberdockeridockerauth
